name: Deploy to VM

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  deploy:
    name: Deploy to Virtual Machine
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up SSH access
      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: |
            ${{ secrets.VM_SSH_KEY }}

      # Step 3: Deploy project files to VM
      - name: Copy Files to VM
        run: |
          echo "Copying files to the VM..."
          scp -o StrictHostKeyChecking=no -r . ${{ secrets.VM_USER }}@${{ secrets.VM_IP }}:/var/www/html/hotel

      # Step 4: Run SQL script on VM
      - name: Execute SQL Script
        run: |
          echo "Running SQL script on the remote database..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} \
          "mysql -u ${{ secrets.DB_USER }} -p'${{ secrets.DB_PASS }}' ${{ secrets.DB_NAME }} < /var/www/html/hotel/bootstrap.sql"

      # Step 5: Confirmation
      - name: Deployment Complete
        run: echo "Deployment to VM completed successfully!"
